### ISSUE TITLE
Question about your chezmoi setup

### ISSUE THREAD

**Issue by elizabeth-dev** [EelisK/dotfiles#1]
Hi, I hope you don't mind me approaching you through a Github Issue 🙈

I'll go straight to the point, I hope you can help me. I've just started using chezmoi to manage my dotfiles, and there's an issue I'm struggling a bit with. I want to add Oh My Zsh through the `.chezmoiexternal.toml` file, and then on top of that, add a custom theme/plugin in the `.oh-my-zsh/custom` folder. The first part is working fine for me, but when I add my custom theme, and then run `chezmoi add .oh-my-zsh/custom/themes/afowler.zsh-theme`, I get a weird error:

```
chezmoi: stat /home/elizabeth/.local/share/chezmoi/exact_themes: no such file or directory
```
I've been checking other people's dotfiles repos, and I see you seem to have accomplished that with a custom Oh My Zsh plugin. May I ask how did you do it?

Thanks in advance for your time!

**Comment by EelisK** [comment]
Hey! Looks like you might have `chezmoi add` confused with `chezmoi apply`. You might want something like this for your setup:
### Files needed
```toml
# Your ~/.local/share/chezmoi/.chezmoiexternal.toml
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
```
```zsh
# Your ~/.zshrc

# set your theme like this
# afowler is already included in the oh-my-zsh installation
# https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="afowler"
```
### Commands for management

```zsh
# Run this to include your .zshrc in chezmoi
# It will create a file dot_zshrc
chezmoi add ~/.zshrc

# If you want to make changes to your ~/.zshrc
# you need to modify `~/.local/share/chezmoi/dot_zshrc`
# once modified, you can apply to changes to your machine as follows:
chezmoi apply 
```

### Additional details

For managing zsh configs with chezmoi, here's how I handle it:

- `.oh-my-zsh` is defined as an external dependency in `.chezmoiexternal.yaml.tmpl`
  - It's important to specify the type as `archive` and not `git-repo`. From [related docs](https://www.chezmoi.io/user-guide/include-files-from-elsewhere/#include-a-subdirectory-from-a-git-repository):
 > Using a git-repo external delegates management of the directory to git. chezmoi cannot manage any other files in that directory.

- I specify any external zsh plugins in `.chezmoiexternal.yaml.tmpl` as subdirectories under `.oh-my-zsh/custom/plugins/`
- I include external zsh completions under a custom plugin `.oh-my-zsh/custom/plugins/external-completions`
- All the external completions will be downloaded there (`kubectx` and `kubens` for now)
- In this directory, I include an empty file `external-completions.plugin.zsh`, so that `oh my zsh` is able to detect it as a valid plugin
- To load this plugin, I add `external-completions` to my list of plugins in `.zshrc`

In case your theme is not the standard `afowler`, you can add your custom themes with a similar workflow :)

Hope this helps in setting up your configurations!

**Comment by elizabeth-dev** [comment]
I was just about to write an update in here! I've been tinkering a bit more, and I think I've actually managed to make it work with the command `chezmoi add --source .local/share/chezmoi .oh-my-zsh/custom/themes/afowler.zsh-theme`... It's a bit weird that that solved the issue, though. 

If I just modified the source repo at `.local/share/chezmoi` as you suggested, I ended up with a weird "Inconsistent state" error when running `chezmoi apply`. I think this might have had to do with the fact that I discovered the `.chezmoiexternal` functionality after setting up chezmoi and having added some Oh My Zsh file, so maybe chezmoi's internal state DB ended up in a weird state. Not sure.

In any case, thanks a lot for your help! :)
